applenews.applenews_template.*:
  type: config_entity
  label: 'Apple News Template'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    node_type:
      type: string
      label: 'Node type'
    columns:
      type: integer
      label: 'Columns'
    width:
      type: integer
      label: 'Width'
    margin:
      type: integer
      label: 'Margin'
    gutter:
      type: integer
      label: 'Gutter'
    components:
      type: sequence
      sequence:
        type: applenews.applenews_component.[%key]

applenews.applenews_component.*:
  type: config_object
  mapping:
    uuid:
      type: string
    id:
      type: string
      label: 'Plugin ID'
    weight:
      type: integer
      label: 'Weight'
    component_layout:
      type: applenews.component_layout
    component_data:
      type: applenews.component_type.[%parent.component_type]

applenews.component_type.text:
  type: mapping
  mapping:
    text:
      type: applenews.field_mapping
    format:
      type: string
      label: 'Format for included text (none, html, or markdown)'

applenews.component_type.image:
  type: mapping
  mapping:
    URL:
      type: applenews.field_mapping
    caption:
      type: applenews.field_mapping

applenews.component_type.nested:
  type: mapping
  mapping:
    components:
      type: sequence
      sequence:
        type: applenews.applenews_component.[%key]

applenews.component_type.divider:
  type: mapping
  mapping:
    stroke_width:
      type: integer
    stroke_color:
      type: string
    stroke_style:
      type: string

applenews.component_layout:
  type: mapping
  mapping:
    column_start:
      type: integer
    column_span:
      type: integer
    margin_top:
      type: integer
    margin_bottom:
      type: integer
    ignore_margin:
      type: string
    ignore_gutter:
      type: string

applenews.field_mapping:
  type: mapping
  mapping:
    field_name:
      type: string
    field_property:
      type: string

applenews.settings:
  type: config_object
  mapping:
    channels:
      type: sequence
      sequence: applenews.channel.[%key]
    endpoint:
      type: string
      label: 'API Endpoint'
    api_key:
      type: string
      label: 'API Key'
    api_secret:
      type: string
      label: 'API Secret'

applenews.channel.*:
  type: mapping
  mapping:
    name:
      type: string
      label: 'Channel Name'
    id:
      type: string
      label: 'Channel ID'
